version: "2"

networks:
  app-tier:
    driver: bridge
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    networks:
      - app-tier
    expose:
    - "2181"

  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    networks:
      - app-tier
    depends_on:
    - zookeeper
    ports:
    - "9092:9092"
    expose:
    - "9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  Producer:
    image: "node:10"
    networks:
      - app-tier
    user: "node"
    depends_on:
      - kafka
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "8081"
    ports:
      - "8081:8081"
    command: "node Producer.js"
    
  Consumer:
    image: "node:10"
    networks:
      - app-tier
    user: "node"
    depends_on:
      - Producer
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "8082"
    ports:
      - "8082:8082"
    command: "bash start_consumer.sh"
     

